server:
  port: 10086
spring:
  application:
    name: springcloud-eureka
eureka:
  client:
    register-with-eureka: false #不用注册到eureka
    fetch-registry: false #是否从eureka中获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/

