server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zongdashu/springcloudStudy.git
  rabbitmq:
    host: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh